# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3

image:
  repository: eu.gcr.io/census-eq-ci/eq-survey-runner
  tag: latest
  pullPolicy: Always

projectId: ""
submissionBucket: ""

service:
  type: NodePort
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.global-static-ip-name: survey-runner
  tls:
    - secretName: tls-cert

resources:
  cpu: "3"
